### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/sotamak1r/anaconda3/envs/py38/lib/python3.8/site-packages/dearpygui/_dearpygui.so) 

### ISSUE THREAD

**Issue by SOTAMak1r** [ashawkey/stable-dreamfusion#103]
### Description

I ran the command below:
python main.py --text "a hamburger" --workspace trial -O --gui

and the whole error is:
File "main.py", line 8, in
from nerf.gui import NeRFGUI
File "/nvme/chenjunyi/dreamfusion/stable-dreamfusion/nerf/gui.py", line 4, in
import dearpygui.dearpygui as dpg
File "/nvme/chenjunyi/anaconda3/envs/dreamfusion/lib/python3.8/site-packages/dearpygui/dearpygui.py", line 22, in
import dearpygui._dearpygui as internal_dpg
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/chenjunyi/anaconda3/envs/py38/lib/python3.8/site-packages/dearpygui/_dearpygui.so)

please help me!

### Steps to Reproduce

1. python main.py --text "a hamburger" --workspace trial -O --gui

### Expected Behavior

please help me solve this error

### Environment

dearpygui Version: 1.8.0
Operating System: CentOS Linux 7 (Core)

**Comment by SOTAMak1r** [comment]
@ashawkey 
Thanks for your answer! I tried to use docker, but there is a new error:

`Traceback (most recent call last):
  File "main.py", line 146, in <module>
    trainer.train(train_loader, valid_loader, max_epoch)
  File "/app/stable-dreamfusion/nerf/utils.py", line 456, in train
    self.train_one_epoch(train_loader)
  File "/app/stable-dreamfusion/nerf/utils.py", line 668, in train_one_epoch
    self.model.update_extra_state()
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/app/stable-dreamfusion/nerf/renderer.py", line 586, in update_extra_state
    sigmas = self.density(cas_xyzs)['sigma'].reshape(-1).detach()
  File "/app/stable-dreamfusion/nerf/network_grid.py", line 150, in density
    sigma, albedo = self.common_forward(x)
  File "/app/stable-dreamfusion/nerf/network_grid.py", line 80, in common_forward
    h = self.encoder(x, bound=self.bound)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/stable-dreamfusion/gridencoder/grid.py", line 149, in forward
    outputs = grid_encode(inputs, self.embeddings, self.offsets, self.per_level_scale, self.base_resolution, inputs.requires_grad, self.gridtype_id, self.align_corners)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/amp/autocast_mode.py", line 110, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/app/stable-dreamfusion/gridencoder/grid.py", line 52, in forward
    outputs = outputs.permute(1, 0, 2).reshape(B, L * C)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`

The resolvement on the Internet is the dismatch between GPU and cuda. However this cannot solve my problem. My GPU is:
NVIDIA A100-SXM4-80GB. Have you ever meet this problem? Please help me.
