### ISSUE TITLE
<title>Error building extension 'nvdiffrast_plugin': ninja: error: loading 'build.ninja' on Windows10

### ISSUE THREAD

**Issue by voruin** [ashawkey/stable-dreamfusion#177]
### Description

Hello,
I got the `ninja: error: loading 'build.ninja'` during building extension 'nvdiffrast_plugin', when call `python main.py --workspace trial -O --test --save_mesh`:
```
==> Saving mesh to trial\mesh
[INFO] marching cubes thresh: 2.5 (4.693106553537769e-34 ~ 69.4495849609375)
[INFO] mesh cleaning: (71092, 3) --> (68409, 3), (141694, 3) --> (136804, 3)
[INFO] mesh decimation: (68409, 3) --> (49971, 3), (136804, 3) --> (100000, 3)
[INFO] running xatlas to unwrap UVs for mesh: v=(49971, 3) f=(100000, 3)
Using C:\Users\Voruin\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\Voruin\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu117\nvdiffrast_plugin\build.ninja...
Building extension module nvdiffrast_plugin...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: loading 'build.ninja': τ│╗τ╗ƒµë╛Σ╕ìσê░µîçσ«ÜτÜäΦ╖»σ╛äπÇé

Traceback (most recent call last):
  File "C:\Users\Voruin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\utils\cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

### Steps to Reproduce

I just installed it according to the readme file. After `python main.py --text "XXXX" --workspace trial -O` finished, I ran `python main.py --workspace trial -O --test --save_mesh`. The videos generated successfully in result folder, but it caused error during save mesh.

### Expected Behavior

Generates the meshe and texture.

### Environment

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 526.98       Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| 23%   26C    P8    12W / 250W |    687MiB / 11264MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

```
Package                 Version
----------------------- ------------
absl-py                 1.4.0
accelerate              0.17.1
cachetools              5.3.0
certifi                 2022.12.7
charset-normalizer      3.1.0
clip                    1.0
colorama                0.4.6
contourpy               1.0.7
cycler                  0.11.0
dearpygui               1.8.0
diffusers               0.14.0
einops                  0.6.0
filelock                3.10.0
fonttools               4.39.2
freqencoder             0.0.0
ftfy                    6.1.1
google-auth             2.16.2
google-auth-oauthlib    0.4.6
gridencoder             0.0.0
grpcio                  1.51.3
huggingface-hub         0.13.3
idna                    3.4
imageio                 2.26.1
imageio-ffmpeg          0.4.8
importlib-metadata      6.1.0
joblib                  1.2.0
kiwisolver              1.4.4
Markdown                3.4.1
markdown-it-py          2.2.0
MarkupSafe              2.1.2
matplotlib              3.7.1
mdurl                   0.1.2
ninja                   1.11.1
numpy                   1.24.2
nvdiffrast              0.3.0
oauthlib                3.2.2
opencv-python           4.7.0.72
packaging               23.0
pandas                  1.5.3
Pillow                  9.4.0
pip                     23.0.1
protobuf                3.20.3
psutil                  5.9.4
pyasn1                  0.4.8
pyasn1-modules          0.2.8
Pygments                2.14.0
PyMCubes                0.1.4
pymeshlab               2022.2.post3
pyparsing               3.0.9
python-dateutil         2.8.2
pytz                    2022.7.1
PyYAML                  6.0
raymarching             0.0.0
regex                   2022.10.31
requests                2.28.2
requests-oauthlib       1.3.1
rich                    13.3.2
rsa                     4.9
scikit-learn            1.2.2
scipy                   1.10.1
setuptools              65.5.0
shencoder               0.0.0
six                     1.16.0
tensorboard             2.12.0
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
tensorboardX            2.6
threadpoolctl           3.1.0
tinycudann              1.7
tokenizers              0.13.2
torch                   1.13.1+cu117
torch-ema               0.3
torchaudio              0.13.1+cu117
torchvision             0.14.1+cu117
tqdm                    4.65.0
transformers            4.27.2
trimesh                 3.20.2
typing_extensions       4.5.0
urllib3                 1.26.15
wcwidth                 0.2.6
Werkzeug                2.2.3
wheel                   0.40.0
xatlas                  0.0.7
zipp                    3.15.0
```

**Comment by ashawkey** [comment]
@voruin Hi, it seems to be related to nvdiffrast. Could you try their examples [here](https://github.com/NVlabs/nvdiffrast)?
