### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'dmtet'

### ISSUE THREAD

**Issue by AreChen** [ashawkey/stable-dreamfusion#222]
### Description

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\stabledream\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\stabledream\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\stabledream\lib\site-packages\gradio\blocks.py", line 1039, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\anaconda3\envs\stabledream\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\stabledream\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\stabledream\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\ProgramData\anaconda3\envs\stabledream\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "H:\git\stable-dreamfusion\gradio_app.py", line 161, in submit
    model = NeRFNetwork(opt)
  File "H:\git\stable-dreamfusion\nerf\network_grid.py", line 44, in __init__
    super().__init__(opt)
  File "H:\git\stable-dreamfusion\nerf\renderer.py", line 266, in __init__
    self.dmtet = opt.dmtet
AttributeError: 'Namespace' object has no attribute 'dmtet'

### Steps to Reproduce

1.run "python gradio_app.py --vram_O"

### Expected Behavior

"python main.py --text "a hamburger" --workspace trial -O --vram_O“
work fine and output 2 video（depth&rgb.mp4）

### Environment

winsows11
torch==1.12.1+cu116
torchvision==0.13.1+cu116
torchaudio==0.12.1

**Comment by sekkit** [comment]
+1, I had the same problem, plz help
