### ISSUE TITLE
 Trying Image to 3d on Colab and showed this error. from nerf.provider import NeRFDataset ModuleNotFoundError: No module named 'nerf'

### ISSUE THREAD

**Issue by decodegu** [ashawkey/stable-dreamfusion#247]
### Description

Trying Image to 3d on Colab and showed this error when I came to the training process
 
The error showed on line 29

from: can't read /var/mail/nerf.provider
/bin/bash: import: command not found
/bin/bash: a: No such file or directory
Traceback (most recent call last):
  File "/content/stable-dreamfusion/pretrained/zero123/main.py", line 5, in <module>
    from nerf.provider import NeRFDataset
ModuleNotFoundError: No module named 'nerf'
Traceback (most recent call last):
  File "/content/stable-dreamfusion/pretrained/zero123/main.py", line 5, in <module>
    from nerf.provider import NeRFDataset
ModuleNotFoundError: No module named 'nerf'
Traceback (most recent call last):
  File "/content/stable-dreamfusion/pretrained/zero123/main.py", line 5, in <module>
    from nerf.provider import NeRFDataset
ModuleNotFoundError: No module named 'nerf'
Traceback (most recent call last):
  File "/content/stable-dreamfusion/pretrained/zero123/main.py", line 5, in <module>
    from nerf.provider import NeRFDataset
ModuleNotFoundError: No module named 'nerf'
Traceback (most recent call last):
  File "/content/stable-dreamfusion/pretrained/zero123/main.py", line 5, in <module>
    from nerf.provider import NeRFDataset
ModuleNotFoundError: No module named 'nerf'
Traceback (most recent call last):
  File "/content/stable-dreamfusion/pretrained/zero123/main.py", line 5, in <module>
    from nerf.provider import NeRFDataset
ModuleNotFoundError: No module named 'nerf'

### Steps to Reproduce

here is the code i ran.

https://colab.research.google.com/drive/1qm2iZRP2Fh2ElRzF9jayjtD1DOoYxshC?usp=sharing

### Expected Behavior

The Zero123 model is loaded and generates new views to improve the image to 3D behavior.

### Environment

Google Colab

**Comment by ashawkey** [comment]
@decodegu Hi, as far as I can see, you `%cd pretrained/omnidata` but forget to `% cd ../..` to the root directory.
