### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by YadaREKI** [ashawkey/stable-dreamfusion#347]
### Description

  File "main.py", line 410, in <module>
    trainer.train(train_loader, valid_loader, test_loader, max_epoch)
  File "/root/autodl-tmp/dreamfusion/nerf/utils.py", line 812, in train
    self.train_one_epoch(train_loader, max_epochs)
  File "/root/autodl-tmp/dreamfusion/nerf/utils.py", line 1037, in train_one_epoch
    self.model.update_extra_state()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/dreamfusion/nerf/renderer.py", line 1123, in update_extra_state
    indices = raymarching.morton3D(coords).long() # [N]
  File "/root/autodl-tmp/dreamfusion/raymarching/raymarching.py", line 112, in forward
    get_backend().morton3D(coords.int(), N, indices)
TypeError: forward() takes 2 positional arguments but 4 were given

### Environment

ubuntu20.04,pytorch 1.12.1+cu116,cuda11.6

**Comment by heguyu** [comment]
also
win10 torch2.0.1,cuda11.8



==> [2024-01-11_15-04-16] Start Training trial Epoch 1/100, lr=0.050000 ...
  0% 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 410, in <module>
    trainer.train(train_loader, valid_loader, test_loader, max_epoch)
  File "D:\project\stable-dreamfusion\nerf\utils.py", line 812, in train
    get_backend().morton3D(coords.int(), N, indices)
  File "D:\coda_envs\stable-dreamfusion\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
TypeError: forward() takes 2 positional arguments but 4 were given
  0% 0/100 [00:00<?, ?it/s]

**Comment by Z-zachary** [comment]
> also win10 torch2.0.1,cuda11.8
> 
> ==> [2024-01-11_15-04-16] Start Training trial Epoch 1/100, lr=0.050000 ... 0% 0/100 [00:00<?, ?it/s]Traceback (most recent call last): File "main.py", line 410, in trainer.train(train_loader, valid_loader, test_loader, max_epoch) File "D:\project\stable-dreamfusion\nerf\utils.py", line 812, in train get_backend().morton3D(coords.int(), N, indices) File "D:\coda_envs\stable-dreamfusion\lib\site-packages\torch\autograd\function.py", line 506, in apply return super().apply(*args, **kwargs) # type: ignore[misc] TypeError: forward() takes 2 positional arguments but 4 were given 0% 0/100 [00:00<?, ?it/s]

Have you solved this problem? I have the same problem and don't know how to solve it！！！！！！！！！！！！！

**Comment by voilet-027** [comment]
Are there any body solve thie problems? I meet the same question.

**Comment by YadaREKI** [comment]
> ### Environment

try another environment
