### ISSUE TITLE
Urgent error:  bash scripts/install_ext.sh error: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by yangluo23** [ashawkey/stable-dreamfusion#361]
### Description

Processing ./raymarching
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: raymarching
  Building wheel for raymarching (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [229 lines of output]
      running bdist_wheel
      running build
      running build_ext
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/utils/cpp_extension.py:353: UserWarning:
      
                                     !! WARNING !!
      
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
      Please use a compiler that is ABI-compatible with GCC 5.0 and above.
      See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.
      
      See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
      for instructions on how to install GCC 5 or higher.
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      
                                    !! WARNING !!
      
        warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.6
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building '_raymarching' extension
      creating /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build
      creating /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38
      creating /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc
      creating /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home
      creating /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721
      creating /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp
      creating /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion
      creating /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching
      creating /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/utils/cpp_extension.py:325: UserWarning:
      
                                     !! WARNING !!
      
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      Your compiler (c++) is not compatible with the compiler Pytorch was
      built with for this platform, which is g++ on linux. Please
      use g++ to to compile your extension. Alternatively, you may
      compile PyTorch from source using c++, and then you can also use
      c++ to compile your extension.
      
      See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
      with compiling PyTorch from source.
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      
                                    !! WARNING !!
      
        warnings.warn(WRONG_COMPILER_WARNING.format(
      Emitting ninja build file /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] c++ -MMD -MF /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/bindings.o.d -pthread -B /hpc/home/connect.dzuo721/.conda/envs/dream/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/TH -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.6/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/include/python3.8 -c -c /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/bindings.cpp -o /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/bindings.o -O3 -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_raymarching -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/bindings.o
      c++ -MMD -MF /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/bindings.o.d -pthread -B /hpc/home/connect.dzuo721/.conda/envs/dream/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/TH -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.6/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/include/python3.8 -c -c /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/bindings.cpp -o /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/bindings.o -O3 -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_raymarching -D_GLIBCXX_USE_CXX11_ABI=0
      c++: 错误：unrecognized command line option ‘-std=c++14’
      [2/2] /usr/local/cuda-11.6/bin/nvcc  -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/TH -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.6/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/include/python3.8 -c -c /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu -o /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_raymarching -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.o
      /usr/local/cuda-11.6/bin/nvcc  -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/TH -I/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.6/include -I/hpc/home/connect.dzuo721/.conda/envs/dream/include/python3.8 -c -c /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu -o /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/build/temp.linux-x86_64-cpython-38/hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_raymarching -D_GLIBCXX_USE_CXX11_ABI=0
      nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
      In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:3,
                       from /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu:5:
      /usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
       #error This file requires compiler and library support for the \
        ^
      In file included from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/core/ATenGeneral.h:3:0,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:13,
                       from /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu:5:
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/macros/Macros.h:143:20: 错误：missing binary operator before token "("
       #if __has_attribute(used)
                          ^
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/macros/Macros.h:223:22: 错误：missing binary operator before token "("
       #elif __has_attribute(always_inline) || defined(__GNUC__)
                            ^
      In file included from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/string_view.h:4:0,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/StringUtil.h:6,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:6,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/core/Generator.h:11,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:14,
                       from /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu:5:
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/C++17.h:16:2: 错误：#error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
       #error \
        ^
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/C++17.h:27:2: 错误：#error You need C++14 to compile PyTorch
       #error You need C++14 to compile PyTorch
        ^
      In file included from /usr/local/cuda-11.6/include/thrust/detail/config/config.h:27:0,
                       from /usr/local/cuda-11.6/include/thrust/detail/config.h:23,
                       from /usr/local/cuda-11.6/include/thrust/complex.h:24,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/complex.h:8,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/Half.h:15,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/core/ScalarType.h:5,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/core/StorageImpl.h:4,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/core/Storage.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/core/TensorImpl.h:8,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/core/GeneratorImpl.h:12,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/core/Generator.h:22,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:14,
                       from /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu:5:
      /usr/local/cuda-11.6/include/thrust/detail/config/cpp_dialect.h:110:13: 警告：Thrust requires at least GCC 5.0. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message. [默认启用]
            THRUST_COMPILER_DEPRECATION(GCC 5.0);
                   ^
      /usr/local/cuda-11.6/include/thrust/detail/config/cpp_dialect.h:128:13: 警告：Thrust requires at least C++14. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message. [默认启用]
            THRUST_COMPILER_DEPRECATION(C++14);
                   ^
      In file included from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/typeid.h:25:0,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/core/ScalarTypeToTypeMeta.h:5,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/core/TensorOptions.h:10,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/core/TensorImpl.h:10,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/core/GeneratorImpl.h:12,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/core/Generator.h:22,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:14,
                       from /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu:5:
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/TypeIndex.h:76:2: 错误：#error "You're running a too old version of GCC. We need GCC 5 or later."
       #error "You're running a too old version of GCC. We need GCC 5 or later."
        ^
      In file included from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3:0,
                       from /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu:6:
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: 错误：#error C++14 or later compatible compiler is required to use PyTorch.
       #error C++14 or later compatible compiler is required to use PyTorch.
        ^
      In file included from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3:0,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                       from /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu:6:
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/ATen.h:4:2: 错误：#error C++14 or later compatible compiler is required to use ATen.
       #error C++14 or later compatible compiler is required to use ATen.
        ^
      In file included from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/record_function.h:8:0,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:9,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:13,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                       from /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu:6:
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/variant.h:243:2: 错误：#error "MPark.Variant requires C++11 support."
       #error "MPark.Variant requires C++11 support."
        ^
      In file included from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:11:0,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:13,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                       from /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                       from /hpc/home/connect.dzuo721/tmp/stable-dreamfusion/raymarching/src/raymarching.cu:6:
      /hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/include/c10/util/LeftRight.h:7:24: 致命错误：shared_mutex：没有那个文件或目录
       #include <shared_mutex>
                              ^
      编译中断。
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
          subprocess.run(
        File "/hpc/home/connect.dzuo721/.conda/envs/dream/lib/python3.8/subprocess.py", line 512, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### Steps to Reproduce

I just followed all the same steps in this repo.  Also, I have followed this [issue](https://github.com/ashawkey/stable-dreamfusion/issues/56#issuecomment-1295030787).  But nothing works.

### Expected Behavior

successfully install cuda extensions:  `bash scripts/install_ext.sh`

### Environment

The envs package:
```shell
>>> import torch
>>> torch.__version__
'1.12.1+cu116'
>>> torch.version.cuda
'11.6'
>>> 
```

and `nvcc -V`: 
```shell
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
```

**Comment by yangluo23** [comment]
OK，I solved this problem. If you have the same issue in the future, please make sure your gcc/g++ version matches your cuda version, and your torch (with cuda) version should also match that. For me, the versions are:
```shell
gcc-10.3.0
cuda-11.7
torch-1.13.1+cu117
```

I highly recommend you follow such [[solution]](https://github.com/ashawkey/stable-dreamfusion/issues/56#issuecomment-1295030787) to install your package. Hope you well.
