### ISSUE TITLE
Failed to import transformers.models.clip.modeling_clip

### ISSUE THREAD

**Issue by Lubnevsky** [ashawkey/stable-dreamfusion#74]
Using Windows 10 and anaconda3. Whenever I try to run main.py, I get this error.

```
Traceback (most recent call last):
  File "C:\Users\plushie\Programs\stable-dreamfusion\main.py", line 138, in <module>
    from nerf.sd import StableDiffusion
  File "C:\Users\plushie\Programs\stable-dreamfusion\nerf\sd.py", line 1, in <module>
    from transformers import CLIPTextModel, CLIPTokenizer, logging
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "C:\Users\plushie\anaconda3\lib\site-packages\transformers\utils\import_utils.py", line 1067, in __getattr__
    value = getattr(module, name)
  File "C:\Users\plushie\anaconda3\lib\site-packages\transformers\utils\import_utils.py", line 1066, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\plushie\anaconda3\lib\site-packages\transformers\utils\import_utils.py", line 1078, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
module 'signal' has no attribute 'SIGKILL'
```

**Comment by Lubnevsky** [comment]
Nvm, located the problem file! C:\Users\plushie\anaconda3\Lib\site-packages\torch\distributed\elastic\timer\file_based_local_timer.py had a lone "SIGKILL" that I had to change to "SIGTERM", now the issue's gone lol
