### ISSUE TITLE
Raymarching build failed

### ISSUE THREAD

**Issue by tonymacx86PRO** [ashawkey/stable-dreamfusion#84]
ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\torch\utils\cpp_extension.py", line 1900, in _run_ninja_build
          subprocess.run(
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Coder\Documents\stable-dreamfusion\raymarching\setup.py", line 44, in <module>
          setup(
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\torch\utils\cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "C:\Users\Coder\.conda\envs\stable-dreamfusion\lib\site-packages\torch\utils\cpp_extension.py", line 1916, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension

Windows 10, python 3.9, Running under Developer Command Prompt (Anaconda)

**Comment by ashawkey** [comment]
Hi, please check the latest pure-pytorch version if the CUDA extensions fail to install.

**Comment by StonERMax** [comment]
My pytorch version is 1.13.1. But it also fails.

**Comment by LauJohnC** [comment]
Ayo, check this out
https://github.com/ashawkey/stable-dreamfusion/issues/56#issuecomment-1756958090
