### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6'

### ISSUE THREAD

**Issue by DuckersMcQuack** [ashawkey/stable-dreamfusion#91]
Tried to add these as well, but to no avail. Reinstalled conda with the needed dependencies as far as i could. But this part i'm now stuck with. error code below image.

![image](https://user-images.githubusercontent.com/9039370/202880241-3765629c-6596-4e29-864e-bb6dc9e4e9bd.png)

`(base)` C:\Users\Duckers>cd C:\stable-dreamfusion-main\stable-dreamfusion

(base) C:\stable-dreamfusion-main\stable-dreamfusion>pip install ./raymarching
Processing c:\stable-dreamfusion-main\stable-dreamfusion\raymarching
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: raymarching
  Building wheel for raymarching (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6'
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\stable-dreamfusion-main\stable-dreamfusion\raymarching\setup.py", line 44, in <module>
          setup(
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Duckers\miniconda3\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\Duckers\miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
          return Version(version)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for raymarching
  Running setup.py clean for raymarching
Failed to build raymarching
Installing collected packages: raymarching
  Attempting uninstall: raymarching
    Found existing installation: raymarching 0.1.3
    Uninstalling raymarching-0.1.3:
      Successfully uninstalled raymarching-0.1.3
  Running setup.py install for raymarching ... error
  error: subprocess-exited-with-error

  × Running setup.py install for raymarching did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6'
      running install
      C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\stable-dreamfusion-main\stable-dreamfusion\raymarching\setup.py", line 44, in <module>
          setup(
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\Duckers\miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
          return Version(version)
        File "C:\Users\Duckers\miniconda3\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of raymarching
  Moving to c:\users\duckers\miniconda3\lib\site-packages\raymarching-0.1.3.dist-info\
   from C:\Users\Duckers\miniconda3\Lib\site-packages\~aymarching-0.1.3.dist-info
  Moving to c:\users\duckers\miniconda3\lib\site-packages\raymarching\
   from C:\Users\Duckers\miniconda3\Lib\site-packages\~aymarching
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> raymarching

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

(base) C:\stable-dreamfusion-main\stable-dreamfusion>``

**Comment by xiazhi1** [comment]
I have the same issue like you , the possible cause may be the CUDA and pytorch is dismathed
you can print this code to test it in python：
```
import torch

print(torch.__version__)  
print(torch.version.cuda)
print(torch.cuda.is_available())


```
Hope this can help you!

**Comment by DuckersMcQuack** [comment]
> 

'import' is not recognized as an internal or external command,
operable program or batch file.

**Comment by JohnRodney** [comment]
Going through the open issues you've had I've followed about the same path as you.

To get past this step I went to https://pytorch.org/get-started/locally/ and filled out the options for my computer like: 
![image](https://user-images.githubusercontent.com/11075982/203616643-72764729-bf44-44bc-a209-97057379b729.png)

Then I pasted the command to my terminal but added `--force-reinstall` to the end of it.  
Then my test.py had a valid output for:
```python
import torch

print(torch.__version__) #1.13.0+cu116
print(torch.version.cuda) #11.6
print(torch.cuda.is_available()) #True
```

I got stuck afterwords with gridencoder failing to build because of file path problems? 
```
Program
c1xx: fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory
EHsc
c1xx: fatal error C1083: Cannot open source file: 'Files/Git/EHsc': No such file or directory
Program
(and about 10 more errors like this)
```

Looked in the path its outputting and those files / directories definitely don't exist.  Tried to dig into where these lines get called and its somewhere in the `nvcc` command.  Since I'm super unfamiliar with `python` in `windows` development and the entire nvidia dev tools kit.  

I'm current not sure if its a problem with arguments passed to nvcc OR and issue with my CUDA setup / install in general.

**Comment by DuckersMcQuack** [comment]
![image](https://user-images.githubusercontent.com/9039370/204111943-ff232c0f-718d-4db3-a181-8cff82ac8af5.png)

Import isn't a valid command.

**Comment by Aidanjosiah02** [comment]
Do
>python
>>> import torch
>>> print(torch.__version__)
etc.

**Comment by Aidanjosiah02** [comment]
In my case I got `1.13.1+cpu`. And from `>print(torch.version.cuda)` I got `None`. So I then used:
`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117 --force-reinstall` since I use cuda 1.17.
Tried `>print(torch.__version__)` again in the Python sub-shell and it returned `1.13.1+cu117`. `>torch.cuda.is_available()` also returned `True`.

**Comment by Aidanjosiah02** [comment]
If you encounter `ModuleNotFoundError: No module named '_gridencoder'`, you may have to edit the "grid.py" file it is referencing which is in the folder "gridencoder". Open it up and on line 10 remove the underscore from "import _gridencoder". Do the same thing for "freqencoder" and "raymarching". These imports reference C header files. The underscore might be how the Linux version of Python interprets those kinds of imports... I don't know. Just a guess.

**Comment by CGMikeG** [comment]
make sure you check pytorch website and get the correct torch and cuda version.

https://pytorch.org/get-started/previous-versions/
