### ISSUE TITLE
RuntimeError: instance mode - pos must have shape [>0, >0, 4]

### ISSUE THREAD

**Issue by vtemian** [ashawkey/stable-dreamfusion#99]
### Description

I'm trying to run the examples from README, but any tries still results in the following error
```
Namespace(text=None, negative='', O=True, O2=False, test=True, save_mesh=True, eval_interval=10, workspace='mytest', guidance='stable-diffusion', seed=0, iters=10000, lr=0.001, ckpt='latest', cuda_ray=True, max_steps=512, num_steps=64, upsample_steps=32, update_extra_interval=16, max_ray_batch=4096, albedo=False, albedo_iters=1000, uniform_sphere_rate=0.5, bg_radius=1.4, density_thresh=10, fp16=True, backbone='grid', w=64, h=64, jitter_pose=False, bound=1, dt_gamma=0, min_near=0.1, radius_range=[1.0, 1.5], fovy_range=[40, 70], dir_text=True, suppress_face=False, angle_overhead=30, angle_front=60, lambda_entropy=0.0001, lambda_opacity=0, lambda_orient=0.01, lambda_smooth=0, gui=False, W=800, H=800, radius=3, fovy=60, light_theta=60, light_phi=0, max_spp=1)
NeRFNetwork(
  (encoder): GridEncoder: input_dim=3 num_levels=16 level_dim=2 resolution=16 -> 2048 per_level_scale=1.3819 params=(903480, 2) gridtype=tiled align_corners=False
  (sigma_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=32, out_features=64, bias=True)
      (1): Linear(in_features=64, out_features=64, bias=True)
      (2): Linear(in_features=64, out_features=4, bias=True)
    )
  )
  (encoder_bg): FreqEncoder: input_dim=3 degree=4 output_dim=27
  (bg_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=27, out_features=64, bias=True)
      (1): Linear(in_features=64, out_features=3, bias=True)
    )
  )
)
[INFO] Trainer: df | 2022-12-01_14-50-33 | cuda | fp16 | mytest
[INFO] #parameters: 1815479
[INFO] Loading latest checkpoint ...
[INFO] Latest checkpoint is mytest/checkpoints/df_ep0050.pth
[INFO] loaded model.
[INFO] load at epoch 50, global step 5000
[WARN] Failed to load optimizer. loaded state dict has a different number of parameter groups
[INFO] loaded scheduler.
[INFO] loaded scaler.
==> Start Test, save results to mytest/results
100% 100/100 [01:52<00:00,  1.12s/it]==> Finished Test.
==> Saving mesh to mytest/mesh
[INFO] running xatlas to unwrap UVs for mesh: v=(0, 3) f=(0, 3)
100% 100/100 [01:55<00:00,  1.16s/it]
Traceback (most recent call last):
  File "/home/vladtemian/stable-dreamfusion/main.py", line 124, in <module>
    trainer.save_mesh(resolution=256)
  File "/home/vladtemian/stable-dreamfusion/nerf/utils.py", line 468, in save_mesh
    self.model.export_mesh(save_path, resolution=resolution)
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/vladtemian/stable-dreamfusion/nerf/renderer.py", line 328, in export_mesh
    _export(v, f)
  File "/home/vladtemian/stable-dreamfusion/nerf/renderer.py", line 224, in _export
    rast, _ = dr.rasterize(glctx, uv.unsqueeze(0), ft, (h, w)) # [1, h, w, 4]
  File "/usr/local/lib/python3.9/dist-packages/nvdiffrast/torch/ops.py", line 310, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
  File "/usr/local/lib/python3.9/dist-packages/nvdiffrast/torch/ops.py", line 248, in forward
    out, out_db = _get_plugin().rasterize_fwd_cuda(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
RuntimeError: instance mode - pos must have shape [>0, >0, 4]
```

I've logged more details
```
[WARN] Failed to load optimizer. loaded state dict has a different number of parameter groups
```

result

### Steps to Reproduce

Follow README instructions

### Expected Behavior

Should work as expected

### Environment

Debian 5.10.149-2, Pytorch 1.13.0+cu117, CUDA Version: 11.7

**Comment by ashawkey** [comment]
@vtemian Hi, I guess this is because the model fails to generate any shape, you could see the mesh has 0 verts and faces. Maybe you could change the prompt or seed and retry?

**Comment by xulinfei-xlf** [comment]
I have met the same question, did you solve the problem？

**Comment by saullas** [comment]
Hey, I have the same problem... Any progress on this issue?
